---
dependencies: []

galaxy_info:
  author: yasser-hawari
  description: "Deletes all instances provisioned in the specified cloud 'openstack' "
  company: "SomeFictitious Company"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.0
  platforms:
    - name: RHEL
      versions:
      - 7
      - 8
  galaxy_tags:
    - three-tier-app
    - osp-instance-delete